#219 : Added maxWidth and maxHeight property to the cropper
Mawi137/ngx-image-cropper pull request #366
Opened 2020-09-07 08:56 UTC by AmoghHegde

Implemented maxWidth and maxHeight property which can be set for the cropper.

2020-10-08 13:23 UTC, Spymannn commented
anyone knows when this branch will be merge ? 

Thanks

2020-10-20 10:49 UTC, itreppert commented
Yeah, would be very nice to have it. @Mawi137
Really need it in a customers project.

2020-10-28 15:01 UTC, Spymannn commented
Still waiting for this branch to be merged... @Mawi137 
any news about it ? is this project "dead" ?

2020-10-28 17:50 UTC, GuilhermeDemoliner commented
Still waiting for this branch to be merged to.... @Mawi137 
Thanks.

2020-11-09 18:59 UTC, Spymannn commented
@Mawi137 ? any news ? is this repo dead or what ?

2020-11-15 22:39 UTC, Mawi137 requested changes

2020-11-15 22:39 UTC, Mawi137 commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
>              if (!this.maintainAspectRatio) {
Normally the cropper takes up the full image and if there's an aspect ratio, it will center the cropper. Would be nice to keep it that way when there's a max height or width set.

2020-11-15 22:39 UTC, Mawi137 commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +        const ratio = this.transformedSize.width / sourceImageElement.offsetWidth;
`this.maxSize.width` can be used instead of `sourceImageElement.offsetWidth`, they should be the same.

2020-11-15 22:39 UTC, Mawi137 commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +        this.cropperScaledMaxWidth = this.cropperMaxWidth > 20? this.cropperMaxWidth : this.maxSize.width;
This part is quite hard to follow, could you make it clearer in the code what should happen if there is a max height or width set? It also seems you assume both will be set, which is not always the case (ratio is applied to both even if only one is set).

Or, why not follow the same logic as for `cropperMinWidth` and `cropperMinHeight`?

2020-11-15 22:39 UTC, Mawi137 commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +        var diffX = this.getClientX(event) - this.moveStart.clientX;
var in TypeScript?

2020-11-15 22:39 UTC, Mawi137 commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +                this.cropper.x1 = Math.min(Math.max(this.moveStart.clientX - (newWidth / 2), this.cropper.x2 - this.cropperScaledMaxWidth/2),
Shouldn't `this.moveStart.clientX` be used instead of `this.cropper.x2`? `clientX` is the middle of the image before pinch zooming (on mobile).

2020-11-15 22:39 UTC, Mawi137 commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +            const imgWidth = imagePosition.x2 - imagePosition.x1;
Is all this new code really necessary? I don't think `imgWidth` can ever be bigger than `scaledMaxWidthWithRatio`.

2020-11-18 12:11 UTC, AmoghHegde commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +        this.cropperScaledMaxWidth = this.cropperMaxWidth > 20? this.cropperMaxWidth : this.maxSize.width;
When maxWidth or maxHeight is not provided in the input, cropperScaledMaxWidth/cropperScaledMaxHeight will be set to maxSize width/height respectively and adjusted according to the aspect ratio. 
For setting the cropperMinWidth/cropperMinHeight, the cropperMinWidth which is provided in input is assigned and the cropperMinHeight is set based on aspect ratio. 
Here, we check whether the cropperScaledMaxWidth/cropperScaledMaxHeight should be reduced based on aspect ratio since neither of them should be more than what is provided in the input.

2020-11-18 12:20 UTC, AmoghHegde commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +        var diffX = this.getClientX(event) - this.moveStart.clientX;
Change to const

2020-11-18 12:20 UTC, AmoghHegde commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +            const imgWidth = imagePosition.x2 - imagePosition.x1;
Not needed. Remove the new code.

2020-11-18 12:21 UTC, AmoghHegde commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +        const ratio = this.transformedSize.width / sourceImageElement.offsetWidth;
Use this.maxSize.width instead of sourceImageElement.offsetWidth

2020-11-18 12:24 UTC, AmoghHegde commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +                this.cropper.x1 = Math.min(Math.max(this.moveStart.clientX - (newWidth / 2), this.cropper.x2 - this.cropperScaledMaxWidth/2),
Change this.cropper.x2 to this.moveStart.clientX

2020-11-18 12:25 UTC, AmoghHegde commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
>              if (!this.maintainAspectRatio) {
How do you recommend I do that?
I have not tested this feature extensively on mobile devices.

2020-11-19 03:59 UTC, AmoghHegde commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
>              if (!this.maintainAspectRatio) {
How do you recommend I do that?

2020-11-19 04:15 UTC, AmoghHegde commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
>              if (!this.maintainAspectRatio) {
Center the cropper when there is max height or width set

2020-11-19 05:10 UTC, AmoghHegde commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
>              if (!this.maintainAspectRatio) {
Done

2020-11-19 05:11 UTC, AmoghHegde commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +        var diffX = this.getClientX(event) - this.moveStart.clientX;
Done

2020-11-19 05:11 UTC, AmoghHegde commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +            const imgWidth = imagePosition.x2 - imagePosition.x1;
Done

2020-11-19 05:11 UTC, AmoghHegde commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +                this.cropper.x1 = Math.min(Math.max(this.moveStart.clientX - (newWidth / 2), this.cropper.x2 - this.cropperScaledMaxWidth/2),
Done

2020-11-19 05:11 UTC, AmoghHegde commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +        const ratio = this.transformedSize.width / sourceImageElement.offsetWidth;
Done

2020-11-19 05:12 UTC, AmoghHegde commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
>              if (!this.maintainAspectRatio) {
Done

2020-11-19 05:26 UTC, AmoghHegde commented
I have fixed the code review comments and resolved the merge conflict. Thanks.

2020-11-22 21:56 UTC, Mawi137 approved these changes

2020-11-22 21:56 UTC, merged

2020-11-22 22:17 UTC, Mawi137 commented
Thanks! Released in version `3.3.0`.