Fix bugs #561 and #572
Mawi137/ngx-image-cropper pull request #573
Opened 2023-08-01 13:35 UTC by loiddy

2023-09-02 10:26 UTC, Mawi137 commented
Hi, this looks great.
I was reading up on why you used `getComputedStyle` and `parseFloat` and found that `getBoundingClientRect` is actually a lot faster with the same result. Could you adapt your code to use `getBoundingClientRect` instead? Like that the `parseFloat` isn't needed either.
https://stackoverflow.com/a/18341704

2023-09-06 21:38 UTC, loiddy commented
Hi! 

I used `getComputedStyle` because any `transform.rotate` or `transform.scale` applied when a new img is loaded is included in the `getBoundingClientRect` data, and we don't need it. I also didn't think of doing the math :) Nice to know this is faster. Thanks!

Doing the math for rotate was a little tricky. The dimensions `getBoundingClientRect` gives us is the boundary box of the rotated img. You can see it in the pic below. The width and height in the console makes a square, but the image is not a square. It has a ratio of 1.5. I'm guessing HTML likes rectangles and uses the bounding box of fancy rotated things.

I tried [this](https://stackoverflow.com/questions/9971230/calculate-rotated-rectangle-size-from-known-bounding-box-coordinates), but it doesn't work with 45º. Not a good fix so, I did my own: 
- rotate `loadedimage.transformed` with the same angle, 
- get ratio between it and `getBoundingClientRect` data
- use ratio with  non-rotated `loadedimage.transformed` to get img size
- divide by scale

![Screenshot 2023-09-06 at 20 14 40](https://github.com/Mawi137/ngx-image-cropper/assets/32738732/f35840ee-afa2-4904-b1e7-b5eda14d63f1)

2023-10-08 16:52 UTC, Mawi137 requested changes
Sorry for taking a while, I wanted to get the time to really read the code carefully because it has gotten way more complex because of the getClientBoundingRect. I think I understand what you did and I would like to merge your PR, I only have 2 remarks.

2023-10-08 16:52 UTC, Mawi137 commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +      const loaded = this.loadedImage!.transformed.size;
I'm wondering whether the loaded image is needed here, can'y you simply rotate the source image back to 0 using your rotateBox method and get the dimensions from that?

2023-10-08 16:52 UTC, Mawi137 commented on projects/ngx-image-cropper/src/lib/services/crop.service.ts
> +    const imagePosition = this.getImagePosition(sourceImage, loadedImage, cropper, settings, maxSize);
Seems like `sourceImage` isn't used anymore in these methods. So I'd replace this argument with the `maxSize`. Also I'd rename `maxSize` to `imageScreenSize` for example, to make it more clear what it is.

2023-10-09 23:10 UTC, loiddy commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +      const loaded = this.loadedImage!.transformed.size;
My brain must've been a bit mushy when I wrote this. It's not rotateBox. It should be getBoundingBox. I'll change it. 

And we can't do that. This function gets the bounding box dimensions from the dimensions of an img using a "simple [soh cah toa](https://www.mathsisfun.com/algebra/sohcahtoa.html)" approach. But to calculate the dimensions of the rotated img from the dimensions of its bounding box we need a more "complex soh cah toa", explained in the link I sent earlier. It does the simple soh cah toa and inverses it, making it more complex :) But it doesn't work with 45º angles. It gives the wrong value of 0,0.

I can draw this out if you want. I understand geometry better when I draw the problem and solution.

To explain the current solution better, cause I did a poor job earlier and also to explain why it needs loaded image... it transforms the loaded img the same way the screen img is transformed, so we can calculate the ratios between their size and apply it to the known size of the loaded img to calculate the screen one. 

Would you like to avoid using the loaded image here? If so, why? In the stackoverflow response they talk about affine transformations. I haven't been able to understand them yet. At first sight they seemed even more complex and my brain went to the solution I sent. But if you don't want the loaded image here I'll try and figure out if we can avoid it using affine transformations. 

I'll wait for your response to send in changes.

2023-10-09 23:21 UTC, loiddy commented on projects/ngx-image-cropper/src/lib/services/crop.service.ts
> +    const imagePosition = this.getImagePosition(sourceImage, loadedImage, cropper, settings, maxSize);
ups, my bad! thanks for catching that! 

I was thinking of renaming maxSize too, but to imageContainer. I'll change it to imageScreenSize.

I might try to convince you to use imageContainer when I send in the image position service :) I need to revise it but I think it might be more intuitive to understand. Maybe.

2023-10-09 23:22 UTC, loiddy commented on projects/ngx-image-cropper/src/lib/services/crop.service.ts
> +    const imagePosition = this.getImagePosition(sourceImage, loadedImage, cropper, settings, maxSize);
Wait. You mean globally right? If so, is it okay if I change it later? I've got more commits ready to push and they use maxSize. Could I push them and when that's been sorted change it?

2023-10-10 00:13 UTC, loiddy commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +      const loaded = this.loadedImage!.transformed.size;
this link is better https://www.mathsisfun.com/sine-cosine-tangent.html

2023-10-12 21:39 UTC, loiddy commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +      const loaded = this.loadedImage!.transformed.size;
I drew it :) 

### Problem 1
We need to know the size of the bounding box (in green). We know the size of the rotated box (in orange).

![Screenshot 2023-10-12 at 21 07 12](https://github.com/Mawi137/ngx-image-cropper/assets/32738732/03c96919-4ee7-4ee8-b293-36dd6f469984)

### Solution to problem 1
Using the SOH CAH TOA approach we can...

width = box.width * cos(a) + box.height * sin(a)
height = box.height * sin(a) + box.width * cos(a)

![Screenshot 2023-10-12 at 21 07 23](https://github.com/Mawi137/ngx-image-cropper/assets/32738732/2f768812-8d26-4973-b375-547c56c3c97f)

The getBoundingBox method in the code first regulates the angle and then does the math. I did a [codepen](https://codepen.io/a_a_a/pen/qBLvyaj) back in the day to test this. You can play with the angles there and comment out code to see why we need to regulate the angle. In the codepen getBoundingBox is a method of the rectangle class. 

### Problem 2
We need to know the size of the rotated box (in orange). We know the size of the bounding box (in green) (we know this because first we found the bounding box of loaded transformed image). 

![Screenshot 2023-10-12 at 21 07 35](https://github.com/Mawi137/ngx-image-cropper/assets/32738732/6e5844ea-b236-42dd-853c-34256433439b)

### Trying to solve problem 2 with solution to problem 1

![Screenshot 2023-10-12 at 23 27 17](https://github.com/Mawi137/ngx-image-cropper/assets/32738732/c9289563-dc06-49b5-ae35-306389b5adb4)

I'm not sure on what corners the 60º angles should go so I drew both ways. You can move the triangles around [here](https://www.geogebra.org/m/k4z9h3wg).

However, baring in mind width and height are the hypotenuse, how would the adjacent and opposite sides add up to the smaller width of the inner rectangle? 

Hopefully this helps :)

2023-10-14 10:28 UTC, Mawi137 commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +      const loaded = this.loadedImage!.transformed.size;
I tried some things out and in the end it seems that getComputedStyle works correctly even when the image is rotated. getBoundingClientRect might have better performance, but it seems like it would be cancelled out by the added logic to calculate the rotation. So getComputedStyle seems like the better option to me now.
Sorry for that, but I didn't think about the rotation either at that time :)

2023-10-14 10:29 UTC, Mawi137 commented on projects/ngx-image-cropper/src/lib/services/crop.service.ts
> +    const imagePosition = this.getImagePosition(sourceImage, loadedImage, cropper, settings, maxSize);
Globally and here, but sure, doesn't matter that much.

2023-10-14 18:31 UTC, loiddy commented on projects/ngx-image-cropper/src/lib/component/image-cropper.component.ts
> +      const loaded = this.loadedImage!.transformed.size;
No problem and sorry I forgot to check performance :/ I'm glad you did.

2023-10-14 18:55 UTC, Mawi137 approved these changes

2023-10-14 18:57 UTC, merged

2023-10-14 19:08 UTC, Mawi137 commented
Released in version 7.1.0. Thanks for your efforts!